name: "action-tar"
author: "Dean Tedesco @developerdino"
description: "This GitHub action exposes the tar command for use in building/archiving"
branding:
  icon: folder-plus
  color: gray-dark
runs:
  using: "docker"
  image: "Dockerfile"
inputs:
  args:
    description: "See developerdino/action-tar README.md for more info"
    required: false
